server:
  port: 8080
spring:
  application:
    name: plant
  profiles:
    active: dve
  datasource:
    url: jdbc:mysql://120.79.34.116:3306/ml_ecai?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ml_ecai
    password: Ftecai#825
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

logging:
  config: classpath:web-logback.xml
  path: D:/plant

